"use client"

import DiscCascadeCarousel, { type DiscCascadeItem } from "@/components/ui/disc-cascade-carousel"

// A made-up studio's catalogue. Every disc label is generated by the
// component, so this demo loads nothing from anywhere.
const films: DiscCascadeItem[] = [
  {
    title: "The Quiet Orchard",
    pattern: "horizon",
    labelStyle: "block",
    palette: ["#c9d6c4", "#26331f", "#e8d9b0"],
    credits: [
      { label: "Directed by", value: "Mara Lindqvist" },
      { label: "Year", value: "2021" },
      { label: "Starring", value: ["Ines Okafor", "Theo Brandt", "Lu Wen"] },
    ],
    reviews: [
      { source: "The Evening Ledger", quote: "Patient, then devastating" },
      { source: "Reel Quarterly", quote: "A garden that keeps its secrets", stars: 4 },
    ],
  },
  {
    title: "Paper Moons",
    pattern: "mosaic",
    palette: ["#f2e3c6", "#d2452b", "#2a5d8f"],
    credits: [
      { label: "Directed by", value: ["Ana Ruiz", "Joel Park"] },
      { label: "Year", value: "2022" },
      { label: "Starring", value: ["Rosa Delgado", "Kit Harlan", "Ama Mensah"] },
    ],
    reviews: [
      { source: "Frame Rate", quote: "Pure handmade joy" },
      { source: "Northside Review", quote: "Folds into your heart" },
    ],
  },
  {
    title: "Somewhere All the Same Night",
    pattern: "sunburst",
    labelStyle: "block",
    palette: ["#f0c94c", "#e8572b", "#2b2622"],
    credits: [
      { label: "Directed by", value: ["Ruth Adeyemi", "Paolo Serra"] },
      { label: "Year", value: "2022" },
      { label: "Starring", value: ["Wen Ito", "Sofia Marr", "Kofi Bell", "June Halloway", "Arlo Pike"] },
    ],
    reviews: [
      { source: "The Paper Lantern", quote: "A carnival inside a kaleidoscope" },
      { source: "Cinephile Weekly", quote: "Maximalist, messy and completely alive" },
    ],
  },
  {
    title: "Velvet Hours",
    pattern: "eclipse",
    palette: ["#141414", "#e9e4da", "#c8a24a"],
    credits: [
      { label: "Directed by", value: ["Tomas Reyna", "Iris Volk"] },
      { label: "Year", value: "2019" },
      { label: "Starring", value: ["Marco Vale", "Celeste Nyx", "Bram Oduya"] },
    ],
    reviews: [
      { source: "Northside Review", quote: "Two hours holding your breath" },
      { source: "The Evening Ledger", quote: "A panic attack in a velvet glove", stars: 4 },
    ],
  },
  {
    title: "Salt & Static",
    pattern: "halftone",
    palette: ["#e9e6df", "#1d1d1d", "#d84b3c"],
    credits: [
      { label: "Directed by", value: "Owen Achterberg" },
      { label: "Year", value: "2023" },
      { label: "Starring", value: ["Freya Moss", "Idris Kane"] },
    ],
    reviews: [
      { source: "Reel Quarterly", quote: "Crackles like a dying radio" },
      { source: "Frame Rate", quote: "Gorgeous, grainy, gone too soon", stars: 4 },
    ],
  },
  {
    title: "Neon Psalms",
    pattern: "rings",
    palette: ["#2d3f7a", "#e8b4c8", "#f4efe6"],
    credits: [
      { label: "Directed by", value: "Priya Natarajan" },
      { label: "Year", value: "2024" },
      { label: "Starring", value: ["Leo Marchetti", "Dee Alvarez", "Sun-hee Park"] },
    ],
    reviews: [
      { source: "The Paper Lantern", quote: "A hymn for the night bus" },
      { source: "Cinephile Weekly", quote: "Hypnotic in every sense" },
    ],
  },
  {
    title: "A Field Guide to Leaving",
    pattern: "stripes",
    labelStyle: "block",
    palette: ["#d9e3df", "#16443f", "#f08a5d"],
    credits: [
      { label: "Directed by", value: "Hollis Grey" },
      { label: "Year", value: "2025" },
      { label: "Starring", value: ["Noor Haddad", "Callum Reyes", "Edie Fenn"] },
    ],
    reviews: [
      { source: "Northside Review", quote: "Quietly the year's best goodbye" },
      { source: "Frame Rate", quote: "Tender as a bruise" },
    ],
  },
]

export default function Demo() {
  // w-full is load-bearing: 21st centres every demo in a flex wrapper, and a
  // flex item left at width:auto shrinks to fit its contents.
  return (
    <div className="w-full">
      <DiscCascadeCarousel
        items={films}
        brand="Lumen"
        nav={[{ label: "Films" }, { label: "Television" }]}
      />
    </div>
  )
}
